common/models/DetailCustomer.php
<?php

namespace common\models;

use yii\helpers\ArrayHelper;

use Yii;

/**
 * This is the model class for table "detail_customer".
 *
 * @property int $detcus_id
 * @property int $detcus_cust_id
 * @property int $detcus_paket_id
 * @property int $detcus_frame_id
 * @property int $detcus_album_id
 * @property int $detcus_foto_id
 * @property int $detcus_harga
 * @property string $detcus_ket
 */
class DetailCustomer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'detail_customer';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['detcus_tanggal', ], 'required'],
            [['detcus_cust_id', 'detcus_pay'], 'integer'],
            [['detcus_tanggal', 'detcus_cust_id', 'detcus_pay', 'detcus_status'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'detcus_id' => 'Detcus ID',
            'detcus_cust_id' => 'No. Invoice',
            'detcus_pay' => 'Sisa Pembayaran',
            'detcus_status' => 'Status Pembayaran',
            'detcus_tanggal' => 'Tanggal'
        ];
    }
    public function getOrderDetailPaketFoto()
    {
        return $this->hasOne(OrderDetailPaketFoto::className(), ['odpf_detcus_id' => 'detcus_id']);
    }

    public function getOrderDetailPaketUpgrade()
    {
        return $this->hasOne(OrderDetailPaketUpgrade::className(), ['odpu_detcus_id' => 'detcus_id']);
    }

    public function getCustomer()
    {
            return $this->hasOne(Customer::className(), ['cust_id' => 'detcus_cust_id']);
    }

    public function getOrderDetailTema()
    {
        return $this->hasOne(OrderDetailTema::className(), ['odtema_detcus_id' => 'detcus_id']);
    }

    public function getDetailServiceSpk()
    {
        return $this->hasOne(DetailServiceSpk::className(), ['serv_detcus_id' => 'detcus_id']);
    }

    public function getFoto()
    {
        return $this->hasOne(Foto::className(), ['foto_detcus_id' => 'detcus_id']);
    }


    public static function retrieveInvoiceLunas(){

        $data =
            self::find()->select([
            'detcus_id' => 'detcus_id',
            'cust_no_invoice' => 'cust_no_invoice'
        ])->joinWith('customer', false)
            ->where('detcus_status = :status', [':status' => 'Lunas'])
            ->asArray()
            ->all()
        ;

        // $customer = Customer::find()->orderBy('cust_no_invoice')->all();
        // $customerList = ArrayHelper::map($customer, 'cust_id', function($customer) {
        //     $detailCustomer = DetailCustomer::findOne(['detcus_cust_id' =>$customer->cust_id]);
        //     $detailCustomer = (['detcus_status' => 'Lunas']);
        //     return $model["cust_no_invoice"];
        // });
    }

}

backend/controllers/DetailCustomerController.php
<?php

namespace backend\controllers;

use Yii;
use yii\helpers\Html;
use common\models\DetailCustomer;
use common\models\OrderDetailPaketFoto;
use common\models\OrderDetailPaketUpgrade;
use common\models\OrderDetailTema;
use common\models\DetailServiceSpk;
use common\models\TemaFoto;
use common\models\TemaFotoSearch;
use common\models\DetailCustomerSearch;
use common\models\Model;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\mpdf\Pdf;
use yii\helpers\Json;

/**
 * DetailCustomerController implements the CRUD actions for DetailCustomer model.
 */
class DetailCustomerController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all DetailCustomer models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new DetailCustomerSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        if(Yii::$app->request->post('hasEditable'))
        {
            $detcusId = Yii::$app->request->post('editableKey');
            $detcus = DetailCustomer::findOne($detcusId);

            $out = Json::encode(['output' => '', 'message' => '']);
            $post = [];
            $posted = current($_POST['DetailCustomer']);
            $post['DetailCustomer'] = $posted;

            if ($detcus->load($post))
            {
                $detcus -> save();
            }
            echo $out;
            return;

        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DetailCustomer model.
     * @param int $detcus_id Detcus ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($detcus_id)
    {
        $rowView = Yii::$app->db->createCommand('SELECT * FROM detail_customer 
        JOIN customer ON customer.cust_id = detail_customer.detcus_cust_id 
        JOIN order_detail_paket_foto ON order_detail_paket_foto.odpf_detcus_id = detail_customer.detcus_id 
        JOIN paket_foto ON paket_foto.paket_id = order_detail_paket_foto.odpf_paket_id
        -- JOIN order_detail_paket_upgrade ON order_detail_paket_upgrade.odpu_detcus_id = detail_customer.detcus_id
        -- JOIN paket_upgrade ON paket_upgrade.upg_id = order_detail_paket_upgrade.odpu_upg_id
        WHERE detcus_id ="'.$detcus_id.'";')->queryOne(); 
        return $this->render('view', [
            'model' => $this->findModel($detcus_id),
            'rowView' => $rowView,
        ]);
        
    }

    /**
     * Creates a new DetailCustomer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new DetailCustomer();
        $modelsOrderDetailPaketFoto = [new OrderDetailPaketFoto];
        $modelsOrderDetailPaketUpgrade = [new OrderDetailPaketUpgrade];
       
        if ($this->request->isPost) {
        
            if ($model->load($this->request->post()) && $model->save()) {

                //ubah format tanggal sebelum disave ke database
               $model->detcus_tanggal = \Yii::$app->formatter->asDate($model->detcus_tanggal, 'yyyy-MM-dd');

               //form tabularinput
               $modelsOrderDetailPaketFoto = Model::createMultiple(OrderDetailPaketFoto::classname());
               Model::loadMultiple($modelsOrderDetailPaketFoto, Yii::$app->request->post());
               $modelsOrderDetailPaketUpgrade = Model::createMultiple(OrderDetailPaketUpgrade::classname());
               Model::loadMultiple($modelsOrderDetailPaketUpgrade, Yii::$app->request->post());

                // validate all models
                $valid = $model->validate();
                $valid = Model::validateMultiple($modelsOrderDetailPaketFoto) && $valid;
                $valid = Model::validateMultiple($modelsOrderDetailPaketUpgrade) && $valid;
            
                if ($valid) {
                    $transaction = \Yii::$app->db->beginTransaction();
                    try {
                        if ($flag = $model->save(false)) {
                            foreach ($modelsOrderDetailPaketFoto as $modelOrderDetailPaketFoto) 
                            {
                                $modelOrderDetailPaketFoto->odpf_detcus_id = $model->detcus_id;
                                if (! ($flag = $modelOrderDetailPaketFoto->save(false)))  {
                                        $transaction->rollBack();
                                        break;
                                    }
                            }
                            foreach ($modelsOrderDetailPaketUpgrade as $modelOrderDetailPaketUpgrade) 
                            {
                                $modelOrderDetailPaketUpgrade->odpu_detcus_id = $model->detcus_id;
                                if (! ($flag = $modelOrderDetailPaketUpgrade->save(false)))  {
                                $transaction->rollBack();
                                break;
                                }
                            }
                            if ($flag) {
                                $transaction->commit();
                                return $this->redirect(['view', 'detcus_id' => $model->detcus_id]);
                            }
                        }
                    } catch (Exception $e) {
                        $transaction->rollBack();
                    }
                }   
             }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'modelsOrderDetailPaketFoto' => (empty($modelsOrderDetailPaketFoto)) ? [new OrderDetailPaketFoto] : $modelsOrderDetailPaketFoto,
            'modelsOrderDetailPaketUpgrade' => (empty($modelsOrderDetailPaketUpgrade)) ? [new OrderDetailPaketFoto] : $modelsOrderDetailPaketUpgrade,
        ]);
        
    }

    /**
     * Updates an existing DetailCustomer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $detcus_id Detcus ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($detcus_id)
    {
        $model = $this->findModel($detcus_id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'detcus_id' => $model->detcus_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DetailCustomer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $detcus_id Detcus ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($detcus_id)
    {
        $this->findModel($detcus_id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DetailCustomer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $detcus_id Detcus ID
     * @return DetailCustomer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($detcus_id)
    {
        if (($model = DetailCustomer::findOne(['detcus_id' => $detcus_id])) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionPototema()
    {
        $modelODTema = TemaFoto::find()->all();
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('pototema', [
                'medias' => $modelODTema,
            ]);
        }else {
           return $this->render('pototema', [
               'medias' => $modelODTema
           ]);
        } 
    }

    public function actionCetakspk($detcus_id) {
        $rowTema = Yii::$app->db->createCommand('SELECT * FROM detail_customer 
        JOIN customer ON customer.cust_id = detail_customer.detcus_cust_id 
        JOIN order_detail_paket_foto ON order_detail_paket_foto.odpf_detcus_id = detail_customer.detcus_id 
        JOIN paket_foto ON paket_foto.paket_id = order_detail_paket_foto.odpf_paket_id 
        JOIN detail_service_spk ON detail_service_spk.serv_detcus_id = detail_customer.detcus_id 
        JOIN paket_kategori ON paket_kategori.kategori_id = paket_foto.paket_kategori_id 
        JOIN tema_foto ON tema_foto.tem_kategori_id = paket_kategori.kategori_id 
        JOIN order_detail_tema ON odtema_detcus_id = detail_customer.detcus_id 
        JOIN karyawan ON kary_id = detail_service_spk.serv_fotografer_id 
        WHERE detcus_id ="'.$detcus_id.'";')->queryOne();

        // get your HTML raw content without any layouts or scripts
        $model = DetailCustomer::findOne($detcus_id);
        $content = $this->renderPartial('cetakspk', ['model' => $model, 'rowTema' => $rowTema,]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $content,

backend/views/detail-customer/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DetailCustomerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="detail-customer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'detcus_id') ?>

    <?= $form->field($model, 'detcus_cust_id') ?>

    <?= $form->field($model, 'detcus_paket_id') ?>

    <?= $form->field($model, 'detcus_frame_id') ?>

    <?= $form->field($model, 'detcus_album_id') ?>

    <?php // echo $form->field($model, 'detcus_foto_id') ?>

    <?php // echo $form->field($model, 'detcus_harga') ?>

    <?php // echo $form->field($model, 'detcus_ket') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/detail-customer/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use kartik\editable\Editable;
use common\models\Transaksi;

/* @var $this yii\web\View */
/* @var $searchModel common\models\DetailCustomerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Report Pembayaran Paket Foto Studio';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="detail-customer-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    yii\bootstrap\Modal::begin(['id' =>'modal']);
    yii\bootstrap\Modal::end();
    ?>

   
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'detcus_tanggal',
                'headerOptions' => ['class' => 'text-center']
            ],
            [
                'label' => 'Nama Customer',
                'headerOptions' => ['class' => 'text-center'],
                'value' => 'customer.cust_nama',

            ],
            [
                'label' => 'No. Invoice',
                'headerOptions' => ['class' => 'text-center'],
                'value' => 'customer.cust_no_invoice',
            ],
            [
                'label' => 'Nama Paket',
                'headerOptions' => ['class' => 'text-center'],
                'value' => 'orderDetailPaketFoto.paketFoto.paket_nama',
            ],
            [
                'label' => 'Qty',
                'headerOptions' => ['class' => 'text-center'],
                'value' => 'orderDetailPaketFoto.odpf_qty',
            ],
            [
                'attribute' => 'detcus_pay',
                'headerOptions' => ['class' => 'text-center'],
                'format' => 'currency',
                //'contentOptions'=>['style'=>'max-width: 100px;vertical-align:middle'],
            ],
            [
                'label' => 'Total Pembayaran',
                'attribute' => 'detcus_pay',
                'headerOptions' => ['class' => 'text-center'],
                'format' => 'currency',
            ],
            [
                'class' => 'kartik\grid\EditableColumn', 
                'header' => 'Status Pembayaran',
                'headerOptions' => ['class' => 'text-center'],
                'attribute' => 'detcus_status',
                'filter' => ["Down Payment" => "DP", "Lunas" => "Lunas"],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Action',
                'headerOptions' => ['class' => 'text-center'],
                'template' => '{leadView} {leadSPK} {leadNota}',
                'buttons' => [
                   'leadNota' => function ($url, $model) {
                    return  Html::a(Yii::t('app', '<i class="fa fa-folder-open"></i>'), 
                    ['detail-customer/preview', 'detcus_id' => $model->detcus_id], 
                    ['class' => 'btn btn-primary pull-center', 'style'=>'margin-center: 5px;', 'id' => 'popupModal', 'title' => 'Nota']);      
                    },
                   'leadSPK' => function ($url, $model) {
                    $url = Url::to(['detail-customer/cetakspk', 'detcus_id' => $model->detcus_id]);
                   return Html::a('<button class="btn btn-primary pull-center" style="margin-center: 5px;"><i class="fa fa-cloud-download"></i> </button>', $url, ['title' => 'SPK']);
                    },
                    'leadView' => function ($url, $model) {
                        $url = Url::to(['detail-customer/view', 'detcus_id' => $model->detcus_id]);
                    return Html::a('<button class="btn btn-primary pull-center" style="margin-center: 5px;"><i class="fa fa-eye-slash"></i> </button>', $url, ['title' => 'Lihat']);
                    },
                   
                ]
            ]
        ],
    ]); ?>

</div>

<?php

$this->registerJs("$(function() {
    $('#popupModal').click(function(e) {
      e.preventDefault();
      $('#modal').modal('show').find('.modal-content')
      .load($(this).attr('href'));
    });
 });");

backend/views/detail-customer/spkfotografer.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\form\ActiveForm;
use kartik\depdrop\DepDrop; 
use kartik\select2\Select2;
use common\models\Karyawan;
use common\models\DetailCustomer;
use yii\helpers\Url;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $model common\models\OrderDetailTema */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
        	<div class="title_left">
				<h3>Form SPK FOTOGRAFER</h3>
			</div>
            <div class="x_title">
                <h2><small>Silahkan Input Paket Foto</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a class="dropdown-item" href="#">Settings 1</a>
                            </li>
                            <li><a class="dropdown-item" href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="customer-form">
                <?php $form = ActiveForm::begin([
					'id' => 'customer-form',
                    // 'type' => ActiveForm::TYPE_HORIZONTAL,
                    // 'formConfig' => ['labelSpan' => 3, 'deviceSize' => ActiveForm::SIZE_SMALL]
                ]); ?>

			 
				<!-- // $data = DetailCustomer::find()
				// 	->select('*')
				// 	->from('detail_customer as detcus')
				// 	->join('JOIN', 'customer as cust', 'detcus.detcus_cust_id = cust.cust_id')
				// 	->join('JOIN', 'order_detail_paket_foto as odpf', 'odpf.odpf_detcus_id = detcus.detcus_id')
				// 	->join('JOIN', 'order_detail_paket_upgrade AS odpu', 'odpu.odpu_detcus_id = detcus.detcus_id')
				// 	->join('JOIN', 'paket_foto as pf', 'pf.paket_id = odpf.odpf_paket_id')
				// 	->join('JOIN', 'paket_upgrade as pu', 'pu.upg_id = odpu.odpu_upg_id')
				// 	->join('JOIN', 'transaksi as trans', 'trans.trans_detcus_id = detcus.detcus_id')
				// 	->asArray();


				// $form->field($modelODTema, 'detcus_cust_id')->widget(AutoComplete::className(), [
				// 	'clientOptions' => [
				// 		'source' => $data,
				// 		'minLength'=>'3', 
				// 		'autoFill'=>true,
				// 		'select' => new JsExpression("function( event, ui ) {
				// 		$('#detcus_id').val(ui.item.detcus_id);//#detcus_id is the id of hiddenInput.
				// 		$('#cust_no_invoice').val(ui.item.cust_no_invoice);
				// 		}"
				// 	)],
				// 	]); -->
			



                <form>
				  <div class="form-row">
				    <div class="form-group col-md-6">
				      <label for="noinvoice">No Invoice</label>
				      <input type="text" class="form-control" id="cust_no_invoice" placeholder="No Invoice" autocomplete="off">
				    </div>
				    <div class="form-group col-md-6">
				      <label for="tgldaftar">Tanggal</label>
				      <input type="text" class="form-control" id="tgldaftar" placeholder="Nama Customer" readonly="readonly">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="namacustomer">Nama Customer</label>
				    <input type="text" class="form-control" id="namacustomer" placeholder="Nama Customer" readonly="readonly">
				  </div>
				  <div class="form-group">
				    <label for="paketfoto">Paket Foto</label>
				    <input type="text" class="form-control" id="paketfoto" placeholder="Nama Paket" readonly="readonly">
				  </div>

				    <div class="form-group col-md-6">
				      <label for="jumlahTema">Jumlah Tema</label>
				      <input type="text" class="form-control" id="jumlahtema" readonly="readonly">
				    </div>
				    <div class="form-group col-md-6">
				      <label for="jumlahPose">Jumlah Pose</label>
				      <input type="text" class="form-control" id="jumlahpose" readonly="readonly">
				    </div>

				
				  <!-- <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#addContactFormModel">
					  <span  class="hand-cursor-pointer quick-add-contact" title="Add Contact">
						  <i class="fa fa-plus-circle" aria-hidden="true"></i>Add Contact Via Model</span>
				  </button> -->

				  <?= Html::a('PILIH POTO TEMA', ['pototema'], ['class' => 'btn btn-primary']) ?>
				  <?= Html::button('PILIH POTO TEMA', ['value' => Url::to(['detail-customer/pototema']), 'title' => 'PILIH POTO TEMA', 'class' => 'showModalButton btn btn-success']); ?>

				  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-sm" >Small modal</button>
				  
				  <div class="form-group">
				    <label for="exampleFormControlTextarea1">Keterangan untuk Tim Foto</label>
				    <textarea class="form-control" id="exampleFormControlTextarea1"></textarea>
				  </div>

				  <div class="form-row">
				    <div class="form-group col-md-3">
				      <label for="inputCity">Studio</label>
				      <input type="text" class="form-control" id="studio">
				    </div>
				    <div class="form-group col-md-3">
				      <label for="inputState">Fotografer</label>
				      <select id="inputState" class="form-control">
				        <option selected>Choose...</option>
				        <option>...</option>
				      </select>
				    </div>
				    <div class="form-group col-md-3">
				      <label for="inputZip">Asisten</label>
				      <input type="text" class="form-control" id="asisten">
				    </div>
				    <div class="form-group col-md-3">
				      <label for="inputZip">CS</label>
				      <input type="text" class="form-control" id="cs">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="form-check">
				      <input class="form-check-input" type="checkbox" id="gridCheck">
				      <label class="form-check-label" for="gridCheck">
				        Check me out
				      </label>
				    </div>
				  </div>
				  <button type="submit" class="btn btn-primary">Sign in</button>
				</form>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>

<?php
// yii\bootstrap\Modal::begin([
//     'headerOptions' => ['id' => 'modalHeader'],
//     'id' => 'modal',
//     'size' => 'modal-lg',
//     'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
// ]);
// echo "<div id='modalContent'></div>";
// yii\bootstrap\Modal::end();
?>

<!-- <script>
	$(function(){
      $(document).on('click', '.showModalButton', function(){
        if ($('#modal').data('bs.modal').isShown) {
            $('#modal').find('#modalContent')
                    .load($(this).attr('value'));
            //dynamiclly set the header for the modal
            document.getElementById('modalHeader').innerHTML = '<h4>' + $(this).attr('title') + '</h4>';
        } else {
            //if modal isn't open; open it and load content
            $('#modal').modal('show')
                    .find('#modalContent')
                    .load($(this).attr('value'));
             //dynamiclly set the header for the modal
            document.getElementById('modalHeader').innerHTML = '<h4>' + $(this).attr('title') + '</h4>';
        }
    });
});
</script> -->

<?php
Modal::begin([
	// 'header'=>'', 
	'id'=>'modal',
	'size'=>'modal-lg',
	'clientOptions' => ['backdrop' => 'dinamis', 'keyboard' => FALSE],
	// 'footer' => ''
]);
echo "<div id='modalContent'></div>";
Modal::end();

$project = (new \yii\db\Query())
        ->select(['cust.cust_no_invoice', 'cust.cust_nama', 'detcus.detcus_tanggal', 'pf.paket_nama', 'pf.paket_harga', 'odpf.odpf_qty', 'pu.upg_nama', 'pu.upg_harga', 'odpu.odpu_qty', 'pf.paket_jumlah_tema', 'pf.paket_pose', 'trans.trans_status', 'trans.trans_pay'])
        ->from('detail_customer as detcus')
        ->join('JOIN', 'customer as cust', 'detcus.detcus_cust_id = cust.cust_id')
        ->join('JOIN', 'order_detail_paket_foto as odpf', 'odpf.odpf_detcus_id = detcus.detcus_id')
        ->join('JOIN', 'order_detail_paket_upgrade AS odpu', 'odpu.odpu_detcus_id = detcus.detcus_id')
        ->join('JOIN', 'paket_foto as pf', 'pf.paket_id = odpf.odpf_paket_id')
        ->join('JOIN', 'paket_upgrade as pu', 'pu.upg_id = odpu.odpu_upg_id')
        ->join('JOIN', 'transaksi as trans', 'trans.trans_detcus_id = detcus.detcus_id');
        //->where(['detcus.detcus_id' => $detcus_id]);

?>

<?php

$this->registerJsFile(
    Yii::$app->request->baseUrl .'/js/detail-customer/juispk.js');